// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUYLWegyR4BIjblCgBIOuL5qZu9UaugFM',
    appId: '1:32486607993:web:bc6f2fca868cf5d58858a8',
    messagingSenderId: '32486607993',
    projectId: 'group-chat-f0b65',
    authDomain: 'group-chat-f0b65.firebaseapp.com',
    storageBucket: 'group-chat-f0b65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd22egJgjj_IiX54WLkRV8bk5sv1YOG3Q',
    appId: '1:32486607993:android:aee520011e2153dd8858a8',
    messagingSenderId: '32486607993',
    projectId: 'group-chat-f0b65',
    storageBucket: 'group-chat-f0b65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-lfMGba6oSyJpN8c_SKMiIuyru25sCyg',
    appId: '1:32486607993:ios:2f98838c86db35de8858a8',
    messagingSenderId: '32486607993',
    projectId: 'group-chat-f0b65',
    storageBucket: 'group-chat-f0b65.appspot.com',
    androidClientId: '32486607993-9aig8mqauojb126nshjknv9evg24ovks.apps.googleusercontent.com',
    iosClientId: '32486607993-a2798h9mcbqq2ailralcou0f7kmkovhq.apps.googleusercontent.com',
    iosBundleId: 'com.massimilianoporzio.hostGroupChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-lfMGba6oSyJpN8c_SKMiIuyru25sCyg',
    appId: '1:32486607993:ios:fa072f7edcf79edf8858a8',
    messagingSenderId: '32486607993',
    projectId: 'group-chat-f0b65',
    storageBucket: 'group-chat-f0b65.appspot.com',
    androidClientId: '32486607993-9aig8mqauojb126nshjknv9evg24ovks.apps.googleusercontent.com',
    iosClientId: '32486607993-p90b80jq6id5pdgqtmdn9uslf92taq44.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostGroupChat',
  );
}
